# Generated by Django 5.0.6 on 2024-06-07 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0003_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\d+$', 'Only numbers allowed')])),
                ('email', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
