# Generated by Django 5.0.6 on 2024-06-07 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0004_details_delete_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
