# Generated by Django 5.0.6 on 2024-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0005_alter_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
