# Generated by Django 5.0.6 on 2024-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0007_details_city_details_social_link_details_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='duration',
        ),
    ]
