# Generated by Django 5.0.6 on 2024-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0008_remove_education_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='Bachelor of Science', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
