# Generated by Django 5.0.6 on 2024-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0009_education_degree_alter_certificate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
    ]
