# Generated by Django 5.0.6 on 2024-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0010_remove_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course_structure',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
