# Generated by Django 5.0.6 on 2024-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0011_education_course_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-from_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', max_length=50),
        ),
    ]
