# Generated by Django 5.0.6 on 2024-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0013_framework_language_remove_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
