# Generated by Django 5.0.6 on 2024-06-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0014_certificate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-from_date']},
        ),
    ]
