# Generated by Django 5.0.6 on 2024-06-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0015_alter_certificate_options_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['from_date']},
        ),
    ]
