# Generated by Django 5.0.6 on 2024-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_website_backend', '0016_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
